language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t shmeve/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true shmeve/docker-react npm run test
deploy:
  provider: elastikbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: " Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-380785891704"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"